name: Lint & Type-check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Lint
        run: |
          npm run lint --workspaces

      - name: Type-check
        run: |
          npm run tsc --workspaces

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ETL dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r etl/requirements.txt

      - name: Ruff lint (ETL)
        run: ruff etl

      - name: Pip check
        run: python -m pip check

      - name: ETL dry-run smoke test
        run: python -m etl.main --dry-run
      

      

          